package net.mograsim.logic.ui.model.components.mi.nandbased.am2901;

import net.haspamelodica.swt.helper.swtobjectwrappers.Point;
import net.mograsim.logic.ui.model.ViewModelModifiable;
import net.mograsim.logic.ui.model.components.GUINandGate;
import net.mograsim.logic.ui.model.components.SimpleRectangularSubmodelComponent;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUIand;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUIdlatch4;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUImux1_4;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUIor4;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUIram4;
import net.mograsim.logic.ui.model.components.mi.nandbased.GUIsel3_4;
import net.mograsim.logic.ui.model.wires.GUIWire;
import net.mograsim.logic.ui.model.wires.Pin;
import net.mograsim.logic.ui.model.wires.WireCrossPoint;

public class GUIAm2901 extends SimpleRectangularSubmodelComponent
{
	public GUIAm2901(ViewModelModifiable model)
	{
		super(model, 1, "GUIAm2901");
		setSubmodelScale(.1);
		setInputPins("I8", "I7", "I6", "I5", "I4", "I3", "I2", "I1", "I0", "C", "Cn", "D1", "D2", "D3", "D4", "A0", "A1", "A2", "A3", "B0",
				"B1", "B2", "B3", "IRAMn", "IRAMn+3", "IQn", "IQn+3");
		setOutputPins("Y1", "Y2", "Y3", "Y4", "F=0", "Cn+4", "OVR", "F3", "ORAMn", "ORAMn+3", "OQn", "OQn+3");
		initSubmodelComponents();
	}

	@SuppressWarnings("unused") // for GUIWires being created
	private void initSubmodelComponents()
	{
		Pin I8 = getSubmodelPin("I8");
		Pin I7 = getSubmodelPin("I7");
		Pin I6 = getSubmodelPin("I6");
		Pin I5 = getSubmodelPin("I5");
		Pin I4 = getSubmodelPin("I4");
		Pin I3 = getSubmodelPin("I3");
		Pin I2 = getSubmodelPin("I2");
		Pin I1 = getSubmodelPin("I1");
		Pin I0 = getSubmodelPin("I0");
		Pin C = getSubmodelPin("C");
		Pin Cn = getSubmodelPin("Cn");
		Pin D1 = getSubmodelPin("D1");
		Pin D2 = getSubmodelPin("D2");
		Pin D3 = getSubmodelPin("D3");
		Pin D4 = getSubmodelPin("D4");
		Pin A0 = getSubmodelPin("A0");
		Pin A1 = getSubmodelPin("A1");
		Pin A2 = getSubmodelPin("A2");
		Pin A3 = getSubmodelPin("A3");
		Pin B0 = getSubmodelPin("B0");
		Pin B1 = getSubmodelPin("B1");
		Pin B2 = getSubmodelPin("B2");
		Pin B3 = getSubmodelPin("B3");
		Pin IRAMn = getSubmodelPin("IRAMn");
		Pin IRAMnplus3 = getSubmodelPin("IRAMn+3");
		Pin IQn = getSubmodelPin("IQn");
		Pin IQnplus3 = getSubmodelPin("IQn+3");
		Pin Y1 = getSubmodelPin("Y1");
		Pin Y2 = getSubmodelPin("Y2");
		Pin Y3 = getSubmodelPin("Y3");
		Pin Y4 = getSubmodelPin("Y4");
		Pin Feq0 = getSubmodelPin("F=0");
		Pin Cnplus4 = getSubmodelPin("Cn+4");
		Pin OVR = getSubmodelPin("OVR");
		Pin F3 = getSubmodelPin("F3");
		Pin ORAMn = getSubmodelPin("ORAMn");
		Pin ORAMnplus3 = getSubmodelPin("ORAMn+3");
		Pin OQn = getSubmodelPin("OQn");
		Pin OQnplus3 = getSubmodelPin("OQn+3");

		GUIAm2901DestDecode destDecode = new GUIAm2901DestDecode(submodelModifiable);
		GUImux1_4 Ymux = new GUImux1_4(submodelModifiable);
		GUIand ramweAnd = new GUIand(submodelModifiable);
		GUINandGate notC = new GUINandGate(submodelModifiable, 1);
		GUIAm2901ALUInclSourceDecodeInclFunctionDecode alu = new GUIAm2901ALUInclSourceDecodeInclFunctionDecode(submodelModifiable);
		GUIor4 Fneq0 = new GUIor4(submodelModifiable);
		GUINandGate notFneq0 = new GUINandGate(submodelModifiable, 1);
		GUIram4 ram = new GUIram4(submodelModifiable);
		GUIdlatch4 QAlatch = new GUIdlatch4(submodelModifiable);
		GUIdlatch4 QBlatch = new GUIdlatch4(submodelModifiable);
		GUIsel3_4 ramDsel = new GUIsel3_4(submodelModifiable);
		GUIsel3_4 qregDsel = new GUIsel3_4(submodelModifiable);
		GUIAm2901QReg qreg = new GUIAm2901QReg(submodelModifiable);

		WireCrossPoint cpC1 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpC2 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpC3 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpC4 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpLSH = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpNSH = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpRSH = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQA1 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQA2 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQA3 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQA4 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ1 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ2 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ3 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ4 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ2Rsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpQ3Rsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF11 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF21 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF31 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF41 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpORAMn = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpORAMnplus3 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF3 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF12 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF22 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF32 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF42 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF13 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF23 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF33 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF43 = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF1Lsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF2Lsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF3Lsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF2Rsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF3Rsh = new WireCrossPoint(submodelModifiable, 1);
		WireCrossPoint cpF4Rsh = new WireCrossPoint(submodelModifiable, 1);

		new GUIWire(submodelModifiable, I8, destDecode.getPin("I8"), new Point[0]);
		new GUIWire(submodelModifiable, I7, destDecode.getPin("I7"), new Point[0]);
		new GUIWire(submodelModifiable, I6, destDecode.getPin("I6"), new Point[0]);
		new GUIWire(submodelModifiable, I5, alu.getPin("I5"), new Point[0]);
		new GUIWire(submodelModifiable, I4, alu.getPin("I4"), new Point[0]);
		new GUIWire(submodelModifiable, I3, alu.getPin("I3"), new Point[0]);
		new GUIWire(submodelModifiable, I2, alu.getPin("I2"), new Point[0]);
		new GUIWire(submodelModifiable, I1, alu.getPin("I1"), new Point[0]);
		new GUIWire(submodelModifiable, I0, alu.getPin("I0"), new Point[0]);
		new GUIWire(submodelModifiable, C, cpC1, new Point[0]);
		new GUIWire(submodelModifiable, cpC1, cpC2, new Point[0]);
		new GUIWire(submodelModifiable, cpC2, notC.getPin("A"), new Point[0]);
		new GUIWire(submodelModifiable, cpC2, notC.getPin("B"), new Point[0]);
		new GUIWire(submodelModifiable, cpC1, cpC3, new Point[0]);
		new GUIWire(submodelModifiable, cpC3, QAlatch.getPin("C"), new Point[0]);
		new GUIWire(submodelModifiable, cpC3, cpC4, new Point[0]);
		new GUIWire(submodelModifiable, cpC4, QBlatch.getPin("C"), new Point[0]);
		new GUIWire(submodelModifiable, cpC4, qreg.getPin("C"), new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("LSH"), cpLSH, new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("NSH"), cpNSH, new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("RSH"), cpRSH, new Point[0]);
		new GUIWire(submodelModifiable, cpLSH, ramDsel.getPin("SA"), new Point[0]);
		new GUIWire(submodelModifiable, cpNSH, ramDsel.getPin("SB"), new Point[0]);
		new GUIWire(submodelModifiable, cpRSH, ramDsel.getPin("SC"), new Point[0]);
		new GUIWire(submodelModifiable, cpLSH, qregDsel.getPin("SA"), new Point[0]);
		new GUIWire(submodelModifiable, cpNSH, qregDsel.getPin("SB"), new Point[0]);
		new GUIWire(submodelModifiable, cpRSH, qregDsel.getPin("SC"), new Point[0]);
		new GUIWire(submodelModifiable, A0, ram.getPin("A0"), new Point[0]);
		new GUIWire(submodelModifiable, A1, ram.getPin("A1"), new Point[0]);
		new GUIWire(submodelModifiable, A2, ram.getPin("A2"), new Point[0]);
		new GUIWire(submodelModifiable, A3, ram.getPin("A3"), new Point[0]);
		new GUIWire(submodelModifiable, B0, ram.getPin("B0"), new Point[0]);
		new GUIWire(submodelModifiable, B1, ram.getPin("B1"), new Point[0]);
		new GUIWire(submodelModifiable, B2, ram.getPin("B2"), new Point[0]);
		new GUIWire(submodelModifiable, B3, ram.getPin("B3"), new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QA1"), cpQA1, new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QA2"), cpQA2, new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QA3"), cpQA3, new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QA4"), cpQA4, new Point[0]);
		new GUIWire(submodelModifiable, cpQA1, Ymux.getPin("I0_1"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA2, Ymux.getPin("I0_2"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA3, Ymux.getPin("I0_3"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA4, Ymux.getPin("I0_4"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA1, QAlatch.getPin("D1"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA2, QAlatch.getPin("D2"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA3, QAlatch.getPin("D3"), new Point[0]);
		new GUIWire(submodelModifiable, cpQA4, QAlatch.getPin("D4"), new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QB1"), QBlatch.getPin("D1"), new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QB2"), QBlatch.getPin("D2"), new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QB3"), QBlatch.getPin("D3"), new Point[0]);
		new GUIWire(submodelModifiable, ram.getPin("QB4"), QBlatch.getPin("D4"), new Point[0]);
		new GUIWire(submodelModifiable, Cn, alu.getPin("Cn"), new Point[0]);
		new GUIWire(submodelModifiable, D1, alu.getPin("D1"), new Point[0]);
		new GUIWire(submodelModifiable, D2, alu.getPin("D2"), new Point[0]);
		new GUIWire(submodelModifiable, D3, alu.getPin("D3"), new Point[0]);
		new GUIWire(submodelModifiable, D4, alu.getPin("D4"), new Point[0]);
		new GUIWire(submodelModifiable, QAlatch.getPin("Q1"), alu.getPin("A1"), new Point[0]);
		new GUIWire(submodelModifiable, QAlatch.getPin("Q2"), alu.getPin("A2"), new Point[0]);
		new GUIWire(submodelModifiable, QAlatch.getPin("Q3"), alu.getPin("A3"), new Point[0]);
		new GUIWire(submodelModifiable, QAlatch.getPin("Q4"), alu.getPin("A4"), new Point[0]);
		new GUIWire(submodelModifiable, QBlatch.getPin("Q1"), alu.getPin("B1"), new Point[0]);
		new GUIWire(submodelModifiable, QBlatch.getPin("Q2"), alu.getPin("B2"), new Point[0]);
		new GUIWire(submodelModifiable, QBlatch.getPin("Q3"), alu.getPin("B3"), new Point[0]);
		new GUIWire(submodelModifiable, QBlatch.getPin("Q4"), alu.getPin("B4"), new Point[0]);
		new GUIWire(submodelModifiable, qreg.getPin("Q1"), cpQ1, new Point[0]);
		new GUIWire(submodelModifiable, qreg.getPin("Q2"), cpQ2, new Point[0]);
		new GUIWire(submodelModifiable, qreg.getPin("Q3"), cpQ3, new Point[0]);
		new GUIWire(submodelModifiable, qreg.getPin("Q4"), cpQ4, new Point[0]);
		new GUIWire(submodelModifiable, cpQ1, alu.getPin("Q1"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ2, alu.getPin("Q2"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ3, alu.getPin("Q3"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ4, alu.getPin("Q4"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ1, OQn, new Point[0]);
		new GUIWire(submodelModifiable, cpQ4, OQnplus3, new Point[0]);
		new GUIWire(submodelModifiable, cpQ2, cpQ2Rsh, new Point[0]);
		new GUIWire(submodelModifiable, cpQ3, cpQ3Rsh, new Point[0]);
		new GUIWire(submodelModifiable, cpQ2Rsh, qregDsel.getPin("C1"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ3Rsh, qregDsel.getPin("C2"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ4, qregDsel.getPin("C3"), new Point[0]);
		new GUIWire(submodelModifiable, IQnplus3, qregDsel.getPin("C4"), new Point[0]);
		new GUIWire(submodelModifiable, IQn, qregDsel.getPin("A1"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ1, qregDsel.getPin("A2"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ2Rsh, qregDsel.getPin("A3"), new Point[0]);
		new GUIWire(submodelModifiable, cpQ3Rsh, qregDsel.getPin("A4"), new Point[0]);
		new GUIWire(submodelModifiable, qregDsel.getPin("Y1"), qreg.getPin("D1"), new Point[0]);
		new GUIWire(submodelModifiable, qregDsel.getPin("Y2"), qreg.getPin("D2"), new Point[0]);
		new GUIWire(submodelModifiable, qregDsel.getPin("Y3"), qreg.getPin("D3"), new Point[0]);
		new GUIWire(submodelModifiable, qregDsel.getPin("Y4"), qreg.getPin("D4"), new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("Cn+4"), Cnplus4, new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("OVR"), OVR, new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("F1"), cpF11, new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("F2"), cpF21, new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("F3"), cpF31, new Point[0]);
		new GUIWire(submodelModifiable, alu.getPin("F4"), cpF41, new Point[0]);
		new GUIWire(submodelModifiable, cpF11, cpORAMn, new Point[0]);
		new GUIWire(submodelModifiable, cpF41, cpORAMnplus3, new Point[0]);
		new GUIWire(submodelModifiable, cpORAMn, ORAMn, new Point[0]);
		new GUIWire(submodelModifiable, cpORAMnplus3, ORAMnplus3, new Point[0]);
		new GUIWire(submodelModifiable, cpORAMnplus3, cpF3, new Point[0]);
		new GUIWire(submodelModifiable, cpF3, F3, new Point[0]);
		new GUIWire(submodelModifiable, cpORAMn, qregDsel.getPin("B1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF21, qregDsel.getPin("B2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF31, qregDsel.getPin("B3"), new Point[0]);
		new GUIWire(submodelModifiable, cpF3, qregDsel.getPin("B4"), new Point[0]);
		new GUIWire(submodelModifiable, cpF11, cpF12, new Point[0]);
		new GUIWire(submodelModifiable, cpF21, cpF22, new Point[0]);
		new GUIWire(submodelModifiable, cpF31, cpF32, new Point[0]);
		new GUIWire(submodelModifiable, cpF41, cpF42, new Point[0]);
		new GUIWire(submodelModifiable, cpF12, Fneq0.getPin("A1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF22, Fneq0.getPin("A2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF32, Fneq0.getPin("A3"), new Point[0]);
		new GUIWire(submodelModifiable, cpF42, Fneq0.getPin("A4"), new Point[0]);
		new GUIWire(submodelModifiable, cpF12, cpF13, new Point[0]);
		new GUIWire(submodelModifiable, cpF22, cpF23, new Point[0]);
		new GUIWire(submodelModifiable, cpF32, cpF33, new Point[0]);
		new GUIWire(submodelModifiable, cpF42, cpF43, new Point[0]);
		new GUIWire(submodelModifiable, cpF13, Ymux.getPin("I1_1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF23, Ymux.getPin("I1_2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF33, Ymux.getPin("I1_3"), new Point[0]);
		new GUIWire(submodelModifiable, cpF43, Ymux.getPin("I1_4"), new Point[0]);
		new GUIWire(submodelModifiable, cpF13, cpF1Lsh, new Point[0]);
		new GUIWire(submodelModifiable, cpF23, cpF2Lsh, new Point[0]);
		new GUIWire(submodelModifiable, cpF33, cpF3Lsh, new Point[0]);
		new GUIWire(submodelModifiable, IRAMn, ramDsel.getPin("A1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF1Lsh, ramDsel.getPin("A2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF2Lsh, ramDsel.getPin("A3"), new Point[0]);
		new GUIWire(submodelModifiable, cpF3Lsh, ramDsel.getPin("A4"), new Point[0]);
		new GUIWire(submodelModifiable, cpF2Lsh, cpF2Rsh, new Point[0]);
		new GUIWire(submodelModifiable, cpF3Lsh, cpF3Rsh, new Point[0]);
		new GUIWire(submodelModifiable, cpF43, cpF4Rsh, new Point[0]);
		new GUIWire(submodelModifiable, cpF1Lsh, ramDsel.getPin("B1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF2Rsh, ramDsel.getPin("B2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF3Rsh, ramDsel.getPin("B3"), new Point[0]);
		new GUIWire(submodelModifiable, cpF4Rsh, ramDsel.getPin("B4"), new Point[0]);
		new GUIWire(submodelModifiable, cpF2Rsh, ramDsel.getPin("C1"), new Point[0]);
		new GUIWire(submodelModifiable, cpF3Rsh, ramDsel.getPin("C2"), new Point[0]);
		new GUIWire(submodelModifiable, cpF4Rsh, ramDsel.getPin("C3"), new Point[0]);
		new GUIWire(submodelModifiable, IRAMnplus3, ramDsel.getPin("C4"), new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("RAMWE"), ramweAnd.getPin("A"), new Point[0]);
		new GUIWire(submodelModifiable, notC.getPin("Y"), ramweAnd.getPin("B"), new Point[0]);
		new GUIWire(submodelModifiable, ramweAnd.getPin("Y"), ram.getPin("WE"), new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("QWE"), qreg.getPin("WE"), new Point[0]);
		new GUIWire(submodelModifiable, destDecode.getPin("YF"), Ymux.getPin("S0"), new Point[0]);
		new GUIWire(submodelModifiable, Ymux.getPin("Y1"), Y1, new Point[0]);
		new GUIWire(submodelModifiable, Ymux.getPin("Y2"), Y2, new Point[0]);
		new GUIWire(submodelModifiable, Ymux.getPin("Y3"), Y3, new Point[0]);
		new GUIWire(submodelModifiable, Ymux.getPin("Y4"), Y4, new Point[0]);
	}
}